#<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
#	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">

#	<include file="classpath:config/db/changelog/00000_initial_schema.sql"
#		relativeToChangelogFile="false" />
#</databaseChangeLog>
databaseChangeLog:
  - include: 
      file: src/main/resources/config/db/changelog/sqls/00000_initial_schema.sql

#  - include: 
#      file: classpath:config/db/changelog/xmls/00000_initial_schema.xml